import './css/style.css'

import { Inter, Playfair_Display, The_Nautigal } from 'next/font/google'


const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap'
})

const playfair = Playfair_Display({
  subsets: ['latin'],
  variable: '--font-playfair-display',
  display: 'swap'
})

const nautigal = The_Nautigal({
  weight: ['400', '700'],  // adjust weights as needed
  subsets: ['latin'],
  variable: '--font-the-nautigal',
  display: 'swap',
  style: 'normal',
  fallback: ['serif']
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${playfair.variable} ${nautigal.variable} font-inter antialiased bg-white text-slate-800 tracking-tight`}>
        {children}
      </body>
    </html>
  )
}
